@startuml
[*] --> Desconocido :sin registrar

state Desconocido {
    
}
state Turno <<choice>>





ViewerProceso --> Viewer : si acepta Condiciones
Desconocido --> Turno :registra como viewer
Turno --> ViewerProceso :si
Turno --> EnProgreso :no 
EnProgreso --> CreadorDeContenido :acepta condiciones y Completa 
CreadorDeContenido --> [*]
Viewer --> [*]
@enduml
